int date_to_days(char* date);
struct car* get_period(struct car* c_in,struct car* this_trip,char* st,char* fin);
int* check_autonomy(struct car* car_info,int autonomy[5]);
int leap_year(int year);
int mounth_days(int mounth, int year);
int data_range(char* date_st, char* date_fin, char* req_st, char* req_fin);
void print_perfomance(struct car* car_info);
struct car* choose_data_range(struct car* car_info,struct car* temp,char* date);
char* today_date(char* date);
int get_weekday(char * str);
char* days_to_date(int g, char* date);
